name: Update GeoJSON File

on:
  push:
    paths:
      - 'path/to/GeoJSON/file/**'

jobs:
  update-geojson:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Force Pull Latest Changes
      run: |
        git config user.name 'github-actions[bot]'
        git config user.email 'github-actions[bot]@users.noreply.github.com'
        git fetch origin
        git reset --hard origin/main

    - name: Update GeoJSON file
      run: |
        # Your commands to update the GeoJSON file
        echo "Updating GeoJSON file"

    - name: Commit and Push Overwriting Remote
      run: |
        git add .
        git commit -m 'Update GeoJSON file' || echo "No changes to commit"
        git push --force origin main
